version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  
  build_docker_image:
   executor: docker/docker
#    auth:
#          username: $CCI_USERNAME
#          password: $CCI_PASSWORD
   steps:
      - setup_remote_docker
      - checkout
      
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Setup Tag
#	   command: echo "export TAG-0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: Build docker image
          command: docker run -e CI=true circlepy/nginx:latest 
# run_integration_tests:
#   docker:
#     - image: circleci/node:13.10.1
#   steps:
#     - checkout
  docker/publish:
    docker:
      - image: circleci/golang:1.15
        
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
#          docker_layer_caching: true
      # build the application image
      - run: docker run -e CI=true circlepy/nginx:latest
      # build and push Docker image
      
  
  deploy_docker_appn:
    docker:
      - image: circleci/node:latest
        
   
#      auth:
#          username: $CCI_USERNAME
#          password: $CCI_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
#      - run: docker --version
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Setup Tag
#	   command: echo "export TAG-0.1.$CIRCLE_SHA1" >> $BASH_ENV
      - run:
          name: Pull/Deploy docker image from dockerhub
          command: |
                   docker run -e CI=true circlepy/nginx:latest
                   echo "Successfully deployment done on Circleci node"
                   
#      - run:
#          name: deploy built docker image
#          command: docker run -p 3002:80 -d harishvarma44/ci-demo-docker:$CIRCLE_BUILD_NUM
         
workflows:
  version: 2.1
  build_test:
    jobs:
       
       - docker/publish
       - build_docker_image
          
       - deploy_docker_appn
          
