version: 2
jobs:
  React:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker run -e CI=true circlepy/nginx:latest
      - run:
          name: Run react Tests
          command: |
            docker run -e CI=true circlepy/nginx:latest
  Express:
      resource_class: medium
      docker:
        - image: docker:18.06.3-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Express application Docker image
            command: |
              docker run -e CI=true circlepy/nginx:latest
        # - run:
        #     name: Run Express Tests
        #     command: |
        #       docker run -e CI=true circlepy/nginx:latest


  ReactMain:
      resource_class: medium
      docker:
        - image: docker:18.06.3-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build react application Docker image
            command: |
              docker run -e CI=true circlepy/nginx:latest
        - run:
            name: Run react Tests
            command: |
              docker run -e CI=true circlepy/nginx:latest
        - deploy:
            name: Push application Docker image
            command: |
              TAG=0.1.$CIRCLE_BUILD_NUM
              echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
              docker run -e CI=true circlepy/nginx:latest
  ExpressMain:
      resource_class: medium
      docker:
        - image: docker:18.06.3-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Express application Docker image
            command: |
              docker run -e CI=true circlepy/nginx:latest
        # - run:
        #     name: Run Express Tests
        #     command: |
        #       docker run -e CI=true circlepy/nginx:latest 
        - deploy:
            name: Push Express application Docker image
            command: |
              TAG=0.1.$CIRCLE_BUILD_NUM
              echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
              docker run -e CI=true circlepy/nginx:latest
workflows:
  version: 2
  build_test:
    jobs:
      - React:
          filters:
            branches:
              ignore:
                - main
                - master
      - Express:
          filters:
            branches:
              ignore:
                - main
                - master
  build_test_Deploy:
    jobs:
      - ReactMain:
          filters:
            branches:
              only:
                - main
                - master
      - ExpressMain:
          filters:
            branches:
              only:
                - main
                - master
